import LocalizedStrings from "react-native-localization";

const strings = new LocalizedStrings({
  pt: {
    welcome: "Bem Vindo",
    findProfessionals: "Encontre profissionais de saúde e marque consultas.",
    startNow: "Comece já!",
    login: "Entrar",
    singUp: "Cadastre-se",
    continue: "Continuar",
    cpf: "CPF",
    password: "Senha",
    confirmPassword: "Confirmar Senha",
    rememberCpf: "Lembrar CPF",
    littlemissing: "Falta Pouco!",
    aboutYourself: "Conte-nos um pouco mais sobre você.",
    fullName: "Nome Completo",
    email: "Email",
    dateOfBirth: "Data de nascimento",
    confirm: "Confirmar",
    cancel: "Cancelar",
    enterYourNumber: "Digite seu número para concluir seu cadastro.",
    myNumber: "Meu Numero",
    codeCity: "DDD",
    internationalCodes: "Códigos Internacionais",
    specialties: "Especialidades",
    inquiries: "Consultas",
    messages: "Mensagens",
    profile: "Perfil",
    search: "Pesquisa",
    unexpectedError: "Erro inesperado",
    authenticationError: "Erro de autenticação, verifique seu CPF e sua senha",
    loginError: "Erro ao efetuar o login",
    emptyFields: "Campos vazios",
    error: "Erro!",
    invalidCpf: "CPF inválido",
    loading: "Carregando...",
    erroStorage: "Não foi possível salvar alguns dados",
    medicalAreas: "Áreas Medicas",
    errorFetchingAreas: "Erro ao buscar Áreas",
    endSession: "Fim de sessão",
    errorfetch: "Erro de busca",
    filters: "Filtros",
    clinics: "Clínicas",
    errorLocation: "Não foi possível pegar sua localização",
    reload: "Recarregar",
    noInternetConnection: "Sem conexão com a internet",
    distance: "Distância",
    dependents: "Dependentes",
    adresses: "Endereços",
    privateConsultation: "Consulta Particular",
    none: "Nenhum",
    medicalAppointment: "Consulta Médica",
    add: "Adicionar",
    noDependents: "Você não possui dependentes registrados",
    noAddresses: "Você não possui endereços registrados",
    registerDependent: "Cadastre seu dependente",
    relationships: "Relacionamentos",
    covenants: "Convênios",
    plans: "Planos",
    invalidDependent: "Nome Dependente Inválido",
    InvalidDateBirth: "Invalid date of birth",
    ForgotPassword: "Esqueceu a senha?"
  },
  en: {
    welcome: "Welcome",
    findProfessionals: "Find health professionals and schedule consultations.",
    startNow: "Start now!",
    login: "Login",
    singUp: "Sign up",
    continue: "Continue",
    cpf: "CPF",
    password: "Password",
    rememberCpf: "Remember CPF",
    confirmPassword: "Confirm Password",
    littlemissing: "Little missing!",
    aboutYourself: "Tell us a little more about yourself.",
    fullName: "Full name",
    email: "Email",
    dateOfBirth: "Date of birth",
    confirm: "Confirm",
    cancel: "Cancel",
    enterYourNumber: "Enter your number to complete your registration",
    myNumber: "My Number",
    codeCity: "DDD",
    internationalCodes: "International Codes",
    specialties: "Specialties",
    inquiries: "Inquiries",
    messages: "Messages",
    profile: "Profile",
    search: "Search",
    unexpectedError: "Unexpected error",
    authenticationError: "Authentication error, check your CPF and password",
    loginError: "Error logging in",
    emptyFields: "Empty fields",
    error: "Error!",
    invalidCpf: "Invalid CPF",
    loading: "Loading...",
    erroStorage: "Some data could not be saved",
    medicalAreas: "Medical Areas",
    errorFetchingAreas: "Error fetching areas",
    endSession: "End of session",
    errorfetch: "Error of fetch",
    filters: "Filters",
    clinics: "Clinics",
    errorLocation: "Could not fetch your location",
    reload: "Reload",
    noInternetConnection: "No internet connection",
    distance: "Distance",
    dependents: "Dependents",
    adresses: "Addresses",
    privateConsultation: "Private Consultation",
    none: "None",
    medicalAppointment: "Medical Appointment",
    add: "Add",
    noDependents: "You have no registered dependents",
    noAddresses: "You do not have registered addresses",
    registerDependent: "Register your dependent",
    relationships: "Relationships",
    covenants: "Covenants",
    plans: "Plans",
    invalidDependent: "Invalid Dependent Name",
    InvalidDateBirth: "Invalid date of birth",
    ForgotPassword: "Forgot password?"
  }
});

export default strings;
